-- +goose Up
-- Identity authoritative data. IDs are generated by trusted application code.
CREATE TABLE users (
    user_id uuid PRIMARY KEY,
    normalized_email text NOT NULL,
    password_hash text NOT NULL,
    account_status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    disabled_at timestamptz,
    CONSTRAINT users_normalized_email_not_empty CHECK (normalized_email <> ''),
    CONSTRAINT users_normalized_email_canonical CHECK (normalized_email = lower(btrim(normalized_email))),
    CONSTRAINT users_password_hash_not_empty CHECK (btrim(password_hash) <> ''),
    CONSTRAINT users_account_status_valid CHECK (account_status IN ('active', 'disabled')),
    CONSTRAINT users_disabled_state_consistent CHECK (
        (account_status = 'active' AND disabled_at IS NULL)
        OR (account_status = 'disabled' AND disabled_at IS NOT NULL)
    ),
    CONSTRAINT users_timestamps_ordered CHECK (updated_at >= created_at),
    CONSTRAINT users_disabled_timestamp_ordered CHECK (disabled_at IS NULL OR disabled_at >= created_at)
);

CREATE UNIQUE INDEX users_normalized_email_uidx ON users (normalized_email);

CREATE TABLE refresh_sessions (
    session_id uuid PRIMARY KEY,
    token_family_id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_digest bytea NOT NULL,
    session_state text NOT NULL,
    replacement_session_id uuid,
    created_at timestamptz NOT NULL,
    replaced_at timestamptz,
    idle_expires_at timestamptz NOT NULL,
    absolute_expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    revocation_reason text,
    network_identity_hash text,
    user_agent text,
    CONSTRAINT refresh_sessions_user_fk
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT refresh_sessions_id_family_unique UNIQUE (session_id, token_family_id),
    CONSTRAINT refresh_sessions_replacement_fk
        FOREIGN KEY (replacement_session_id, token_family_id)
        REFERENCES refresh_sessions (session_id, token_family_id)
        ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT refresh_sessions_digest_length CHECK (octet_length(token_digest) = 32),
    CONSTRAINT refresh_sessions_state_valid CHECK (session_state IN ('active', 'replaced', 'revoked', 'expired')),
    CONSTRAINT refresh_sessions_not_self_replacing CHECK (replacement_session_id IS NULL OR replacement_session_id <> session_id),
    CONSTRAINT refresh_sessions_expiry_ordered CHECK (
        idle_expires_at > created_at
        AND absolute_expires_at > created_at
        AND idle_expires_at <= absolute_expires_at
    ),
    CONSTRAINT refresh_sessions_replaced_timestamp_ordered CHECK (replaced_at IS NULL OR replaced_at >= created_at),
    CONSTRAINT refresh_sessions_revoked_timestamp_ordered CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT refresh_sessions_revocation_reason_bounded CHECK (
        revocation_reason IS NULL
        OR (btrim(revocation_reason) <> '' AND char_length(revocation_reason) <= 128)
    ),
    CONSTRAINT refresh_sessions_network_identity_bounded CHECK (
        network_identity_hash IS NULL
        OR (btrim(network_identity_hash) <> '' AND char_length(network_identity_hash) <= 128)
    ),
    CONSTRAINT refresh_sessions_user_agent_bounded CHECK (
        user_agent IS NULL
        OR (btrim(user_agent) <> '' AND char_length(user_agent) <= 512)
    ),
    CONSTRAINT refresh_sessions_state_consistent CHECK (
        (
            session_state = 'active'
            AND replacement_session_id IS NULL
            AND replaced_at IS NULL
            AND revoked_at IS NULL
            AND revocation_reason IS NULL
        )
        OR (
            session_state = 'replaced'
            AND replacement_session_id IS NOT NULL
            AND replaced_at IS NOT NULL
            AND revoked_at IS NULL
            AND revocation_reason IS NULL
        )
        OR (
            session_state = 'revoked'
            AND revoked_at IS NOT NULL
            AND revocation_reason IS NOT NULL
        )
        OR (
            session_state = 'expired'
            AND replacement_session_id IS NULL
            AND replaced_at IS NULL
            AND revoked_at IS NULL
            AND revocation_reason IS NULL
        )
    )
);

CREATE UNIQUE INDEX refresh_sessions_token_digest_uidx ON refresh_sessions (token_digest);
CREATE UNIQUE INDEX refresh_sessions_one_active_family_uidx
    ON refresh_sessions (token_family_id)
    WHERE session_state = 'active';
CREATE INDEX refresh_sessions_family_created_idx
    ON refresh_sessions (token_family_id, created_at);
CREATE INDEX refresh_sessions_user_created_idx
    ON refresh_sessions (user_id, created_at);
CREATE INDEX refresh_sessions_active_expiry_idx
    ON refresh_sessions (absolute_expires_at, idle_expires_at)
    WHERE session_state = 'active';

-- Platform-owned append-only security evidence. The approved query surface only appends.
CREATE TABLE audit_logs (
    audit_event_id uuid PRIMARY KEY,
    occurred_at timestamptz NOT NULL,
    action text NOT NULL,
    result text NOT NULL,
    severity text NOT NULL,
    actor_user_id uuid,
    correlation_id text NOT NULL,
    session_id uuid,
    token_family_id uuid,
    network_identity_hash text,
    user_agent text,
    CONSTRAINT audit_logs_actor_fk
        FOREIGN KEY (actor_user_id) REFERENCES users (user_id) ON DELETE RESTRICT,
    CONSTRAINT audit_logs_action_valid CHECK (action IN (
        'registration_success',
        'registration_failure',
        'login_success',
        'login_failure',
        'refresh_success',
        'refresh_failure',
        'logout',
        'token_family_revocation',
        'refresh_token_reuse',
        'disabled_account_rejection'
    )),
    CONSTRAINT audit_logs_result_valid CHECK (result IN ('success', 'failure')),
    CONSTRAINT audit_logs_severity_valid CHECK (severity IN ('info', 'warning', 'high')),
    CONSTRAINT audit_logs_correlation_id_valid CHECK (
        char_length(correlation_id) BETWEEN 1 AND 128
        AND correlation_id ~ '^[A-Za-z0-9._-]+$'
    ),
    CONSTRAINT audit_logs_network_identity_bounded CHECK (
        network_identity_hash IS NULL
        OR (btrim(network_identity_hash) <> '' AND char_length(network_identity_hash) <= 128)
    ),
    CONSTRAINT audit_logs_user_agent_bounded CHECK (
        user_agent IS NULL
        OR (btrim(user_agent) <> '' AND char_length(user_agent) <= 512)
    )
);

-- Platform-owned operational events. derived_key stores only a 32-byte HMAC result.
CREATE TABLE auth_rate_limit_events (
    event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    derived_key bytea NOT NULL,
    policy_name text NOT NULL,
    policy_version text NOT NULL,
    occurred_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    CONSTRAINT auth_rate_limit_events_derived_key_length CHECK (octet_length(derived_key) = 32),
    CONSTRAINT auth_rate_limit_events_policy_name_valid CHECK (policy_name IN (
        'login_email_failure',
        'login_ip_attempt',
        'registration_ip_attempt',
        'refresh_family_attempt'
    )),
    CONSTRAINT auth_rate_limit_events_policy_version_valid CHECK (policy_version = 'v1'),
    CONSTRAINT auth_rate_limit_events_expiry_ordered CHECK (expires_at > occurred_at)
);

CREATE INDEX auth_rate_limit_events_window_idx
    ON auth_rate_limit_events (policy_name, policy_version, derived_key, expires_at);
CREATE INDEX auth_rate_limit_events_expiry_idx
    ON auth_rate_limit_events (expires_at);

-- +goose Down
DROP TABLE auth_rate_limit_events;
DROP TABLE audit_logs;
DROP TABLE refresh_sessions;
DROP TABLE users;
