// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: authentication_audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuthenticationAuditEvent = `-- name: AppendAuthenticationAuditEvent :one
INSERT INTO audit_logs (
    audit_event_id,
    occurred_at,
    action,
    result,
    severity,
    actor_user_id,
    correlation_id,
    session_id,
    token_family_id,
    network_identity_hash,
    user_agent
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING audit_event_id, occurred_at, action, result, severity, actor_user_id, correlation_id, session_id, token_family_id, network_identity_hash, user_agent
`

type AppendAuthenticationAuditEventParams struct {
	AuditEventID        pgtype.UUID
	OccurredAt          pgtype.Timestamptz
	Action              string
	Result              string
	Severity            string
	ActorUserID         pgtype.UUID
	CorrelationID       string
	SessionID           pgtype.UUID
	TokenFamilyID       pgtype.UUID
	NetworkIdentityHash pgtype.Text
	UserAgent           pgtype.Text
}

// Authentication audit evidence is append-only. No update or delete query is provided.
func (q *Queries) AppendAuthenticationAuditEvent(ctx context.Context, arg AppendAuthenticationAuditEventParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, appendAuthenticationAuditEvent,
		arg.AuditEventID,
		arg.OccurredAt,
		arg.Action,
		arg.Result,
		arg.Severity,
		arg.ActorUserID,
		arg.CorrelationID,
		arg.SessionID,
		arg.TokenFamilyID,
		arg.NetworkIdentityHash,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.AuditEventID,
		&i.OccurredAt,
		&i.Action,
		&i.Result,
		&i.Severity,
		&i.ActorUserID,
		&i.CorrelationID,
		&i.SessionID,
		&i.TokenFamilyID,
		&i.NetworkIdentityHash,
		&i.UserAgent,
	)
	return i, err
}
