// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: authentication_rate_limits.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAuthRateLimitAdvisoryLock = `-- name: AcquireAuthRateLimitAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Must run inside the rate-limit transaction. lock_key is deterministically derived by the future
// runtime adapter from the policy namespace and HMAC-derived key; raw email/IP input is forbidden.
func (q *Queries) AcquireAuthRateLimitAdvisoryLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, acquireAuthRateLimitAdvisoryLock, lockKey)
	return err
}

const clearLoginEmailFailureEvents = `-- name: ClearLoginEmailFailureEvents :execrows
DELETE FROM auth_rate_limit_events
WHERE
    policy_name = 'login_email_failure'
    AND policy_version = $1
    AND derived_key = $2
`

type ClearLoginEmailFailureEventsParams struct {
	PolicyVersion string
	DerivedKey    []byte
}

func (q *Queries) ClearLoginEmailFailureEvents(ctx context.Context, arg ClearLoginEmailFailureEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearLoginEmailFailureEvents, arg.PolicyVersion, arg.DerivedKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveAuthRateLimitEvents = `-- name: CountActiveAuthRateLimitEvents :one
SELECT count(*)
FROM auth_rate_limit_events
WHERE
    policy_name = $1
    AND policy_version = $2
    AND derived_key = $3
    AND expires_at > $4
`

type CountActiveAuthRateLimitEventsParams struct {
	PolicyName    string
	PolicyVersion string
	DerivedKey    []byte
	AsOf          pgtype.Timestamptz
}

func (q *Queries) CountActiveAuthRateLimitEvents(ctx context.Context, arg CountActiveAuthRateLimitEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAuthRateLimitEvents,
		arg.PolicyName,
		arg.PolicyVersion,
		arg.DerivedKey,
		arg.AsOf,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredAuthRateLimitEventsForKey = `-- name: DeleteExpiredAuthRateLimitEventsForKey :execrows
DELETE FROM auth_rate_limit_events
WHERE
    policy_name = $1
    AND policy_version = $2
    AND derived_key = $3
    AND expires_at <= $4
`

type DeleteExpiredAuthRateLimitEventsForKeyParams struct {
	PolicyName    string
	PolicyVersion string
	DerivedKey    []byte
	AsOf          pgtype.Timestamptz
}

func (q *Queries) DeleteExpiredAuthRateLimitEventsForKey(ctx context.Context, arg DeleteExpiredAuthRateLimitEventsForKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthRateLimitEventsForKey,
		arg.PolicyName,
		arg.PolicyVersion,
		arg.DerivedKey,
		arg.AsOf,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGloballyExpiredAuthRateLimitEvents = `-- name: DeleteGloballyExpiredAuthRateLimitEvents :execrows
DELETE FROM auth_rate_limit_events
WHERE expires_at <= $1
`

func (q *Queries) DeleteGloballyExpiredAuthRateLimitEvents(ctx context.Context, asOf pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGloballyExpiredAuthRateLimitEvents, asOf)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEarliestActiveAuthRateLimitExpiry = `-- name: GetEarliestActiveAuthRateLimitExpiry :one
SELECT min(expires_at)::timestamptz
FROM auth_rate_limit_events
WHERE
    policy_name = $1
    AND policy_version = $2
    AND derived_key = $3
    AND expires_at > $4
`

type GetEarliestActiveAuthRateLimitExpiryParams struct {
	PolicyName    string
	PolicyVersion string
	DerivedKey    []byte
	AsOf          pgtype.Timestamptz
}

func (q *Queries) GetEarliestActiveAuthRateLimitExpiry(ctx context.Context, arg GetEarliestActiveAuthRateLimitExpiryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getEarliestActiveAuthRateLimitExpiry,
		arg.PolicyName,
		arg.PolicyVersion,
		arg.DerivedKey,
		arg.AsOf,
	)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAuthRateLimitEvent = `-- name: InsertAuthRateLimitEvent :one
INSERT INTO auth_rate_limit_events (
    derived_key,
    policy_name,
    policy_version,
    occurred_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING event_id, derived_key, policy_name, policy_version, occurred_at, expires_at
`

type InsertAuthRateLimitEventParams struct {
	DerivedKey    []byte
	PolicyName    string
	PolicyVersion string
	OccurredAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) InsertAuthRateLimitEvent(ctx context.Context, arg InsertAuthRateLimitEventParams) (AuthRateLimitEvent, error) {
	row := q.db.QueryRow(ctx, insertAuthRateLimitEvent,
		arg.DerivedKey,
		arg.PolicyName,
		arg.PolicyVersion,
		arg.OccurredAt,
		arg.ExpiresAt,
	)
	var i AuthRateLimitEvent
	err := row.Scan(
		&i.EventID,
		&i.DerivedKey,
		&i.PolicyName,
		&i.PolicyVersion,
		&i.OccurredAt,
		&i.ExpiresAt,
	)
	return i, err
}
