// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: consumer_dedup.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordPlatformConsumerDeduplication = `-- name: RecordPlatformConsumerDeduplication :one
WITH inserted AS (
    INSERT INTO platform_consumer_deduplications (
        consumer_name,
        event_id,
        processed_at
    ) VALUES (
        $1,
        $2,
        $3
    )
    ON CONFLICT (consumer_name, event_id) DO NOTHING
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
`

type RecordPlatformConsumerDeduplicationParams struct {
	ConsumerName string
	EventID      pgtype.UUID
	ProcessedAt  pgtype.Timestamptz
}

// The caller controls the DBTX so this durable marker can commit atomically
// with the consuming side effect. true means this consumer has not processed
// this event before; false means an existing marker won the race.
func (q *Queries) RecordPlatformConsumerDeduplication(ctx context.Context, arg RecordPlatformConsumerDeduplicationParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordPlatformConsumerDeduplication, arg.ConsumerName, arg.EventID, arg.ProcessedAt)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
