// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	AuditEventID        pgtype.UUID
	OccurredAt          pgtype.Timestamptz
	Action              string
	Result              string
	Severity            string
	ActorUserID         pgtype.UUID
	CorrelationID       string
	SessionID           pgtype.UUID
	TokenFamilyID       pgtype.UUID
	NetworkIdentityHash pgtype.Text
	UserAgent           pgtype.Text
	PortfolioID         pgtype.UUID
	TransactionID       pgtype.UUID
	CorrectionID        pgtype.UUID
}

type AuthRateLimitEvent struct {
	EventID       int64
	DerivedKey    []byte
	PolicyName    string
	PolicyVersion string
	OccurredAt    pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
}

type PlatformOutboxEvent struct {
	EventID          pgtype.UUID
	EventType        string
	EventVersion     int32
	AggregateType    string
	AggregateID      pgtype.UUID
	PortfolioID      pgtype.UUID
	TransactionID    pgtype.UUID
	CorrectionID     pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	CorrelationID    string
	Payload          []byte
	PublicationState string
	AttemptCount     int32
	NextAttemptAt    pgtype.Timestamptz
	ClaimedAt        pgtype.Timestamptz
	ClaimToken       pgtype.UUID
	LeaseExpiresAt   pgtype.Timestamptz
	PublishedAt      pgtype.Timestamptz
	LastFailureCode  pgtype.Text
}
