// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendPlatformOutboxEvent = `-- name: AppendPlatformOutboxEvent :one
INSERT INTO platform_outbox_events (
    event_id,
    event_type,
    event_version,
    aggregate_type,
    aggregate_id,
    portfolio_id,
    transaction_id,
    correction_id,
    occurred_at,
    correlation_id,
    payload,
    publication_state,
    attempt_count,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    'PENDING',
    0,
    $12
)
RETURNING event_id, event_type, event_version, aggregate_type, aggregate_id, portfolio_id, transaction_id, correction_id, occurred_at, correlation_id, payload, publication_state, attempt_count, next_attempt_at, claimed_at, claim_token, lease_expires_at, published_at, last_failure_code
`

type AppendPlatformOutboxEventParams struct {
	EventID       pgtype.UUID
	EventType     string
	EventVersion  int32
	AggregateType string
	AggregateID   pgtype.UUID
	PortfolioID   pgtype.UUID
	TransactionID pgtype.UUID
	CorrectionID  pgtype.UUID
	OccurredAt    pgtype.Timestamptz
	CorrelationID string
	Payload       []byte
	NextAttemptAt pgtype.Timestamptz
}

// The caller controls the DBTX. Supplying a pgx.Tx makes this append part of
// the caller's authoritative write transaction.
func (q *Queries) AppendPlatformOutboxEvent(ctx context.Context, arg AppendPlatformOutboxEventParams) (PlatformOutboxEvent, error) {
	row := q.db.QueryRow(ctx, appendPlatformOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.EventVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.PortfolioID,
		arg.TransactionID,
		arg.CorrectionID,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.Payload,
		arg.NextAttemptAt,
	)
	var i PlatformOutboxEvent
	err := row.Scan(
		&i.EventID,
		&i.EventType,
		&i.EventVersion,
		&i.AggregateType,
		&i.AggregateID,
		&i.PortfolioID,
		&i.TransactionID,
		&i.CorrectionID,
		&i.OccurredAt,
		&i.CorrelationID,
		&i.Payload,
		&i.PublicationState,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ClaimedAt,
		&i.ClaimToken,
		&i.LeaseExpiresAt,
		&i.PublishedAt,
		&i.LastFailureCode,
	)
	return i, err
}

const claimDuePlatformOutboxEvents = `-- name: ClaimDuePlatformOutboxEvents :many
WITH candidates AS (
    SELECT candidate.event_id
    FROM platform_outbox_events AS candidate
    WHERE (
        (candidate.publication_state = 'PENDING' AND candidate.next_attempt_at <= $1)
        OR (
            candidate.publication_state = 'PROCESSING'
            AND candidate.lease_expires_at <= $1
        )
    )
    AND NOT EXISTS (
        SELECT 1
        FROM platform_outbox_events AS predecessor
        WHERE predecessor.aggregate_type = candidate.aggregate_type
          AND predecessor.aggregate_id = candidate.aggregate_id
          AND predecessor.publication_state <> 'PUBLISHED'
          AND (predecessor.occurred_at, predecessor.event_id)
              < (candidate.occurred_at, candidate.event_id)
    )
    ORDER BY candidate.occurred_at ASC, candidate.event_id ASC
    LIMIT $4::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE platform_outbox_events AS event
SET publication_state = 'PROCESSING',
    attempt_count = event.attempt_count + 1,
    claimed_at = $1,
    claim_token = $2,
    lease_expires_at = $3
FROM candidates
WHERE event.event_id = candidates.event_id
RETURNING event.event_id, event.event_type, event.event_version, event.aggregate_type, event.aggregate_id, event.portfolio_id, event.transaction_id, event.correction_id, event.occurred_at, event.correlation_id, event.payload, event.publication_state, event.attempt_count, event.next_attempt_at, event.claimed_at, event.claim_token, event.lease_expires_at, event.published_at, event.last_failure_code
`

type ClaimDuePlatformOutboxEventsParams struct {
	AsOf           pgtype.Timestamptz
	ClaimToken     pgtype.UUID
	LeaseExpiresAt pgtype.Timestamptz
	BatchLimit     int32
}

// This single statement uses SKIP LOCKED and an aggregate-stream predecessor
// check, so concurrent workers cannot own the same live claim or overtake an
// unpublished predecessor in one aggregate stream.
func (q *Queries) ClaimDuePlatformOutboxEvents(ctx context.Context, arg ClaimDuePlatformOutboxEventsParams) ([]PlatformOutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimDuePlatformOutboxEvents,
		arg.AsOf,
		arg.ClaimToken,
		arg.LeaseExpiresAt,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformOutboxEvent{}
	for rows.Next() {
		var i PlatformOutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.EventVersion,
			&i.AggregateType,
			&i.AggregateID,
			&i.PortfolioID,
			&i.TransactionID,
			&i.CorrectionID,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.Payload,
			&i.PublicationState,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.ClaimedAt,
			&i.ClaimToken,
			&i.LeaseExpiresAt,
			&i.PublishedAt,
			&i.LastFailureCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClaimedPlatformOutboxEventDeadLetter = `-- name: MarkClaimedPlatformOutboxEventDeadLetter :execrows
UPDATE platform_outbox_events
SET publication_state = 'DEAD_LETTER',
    claimed_at = NULL,
    claim_token = NULL,
    lease_expires_at = NULL,
    last_failure_code = $1
WHERE event_id = $2
  AND publication_state = 'PROCESSING'
  AND claim_token = $3
`

type MarkClaimedPlatformOutboxEventDeadLetterParams struct {
	LastFailureCode pgtype.Text
	EventID         pgtype.UUID
	ClaimToken      pgtype.UUID
}

func (q *Queries) MarkClaimedPlatformOutboxEventDeadLetter(ctx context.Context, arg MarkClaimedPlatformOutboxEventDeadLetterParams) (int64, error) {
	result, err := q.db.Exec(ctx, markClaimedPlatformOutboxEventDeadLetter, arg.LastFailureCode, arg.EventID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPlatformOutboxEventPublished = `-- name: MarkPlatformOutboxEventPublished :execrows
UPDATE platform_outbox_events
SET publication_state = 'PUBLISHED',
    claimed_at = NULL,
    claim_token = NULL,
    lease_expires_at = NULL,
    published_at = $1,
    last_failure_code = NULL
WHERE event_id = $2
  AND publication_state = 'PROCESSING'
  AND claim_token = $3
`

type MarkPlatformOutboxEventPublishedParams struct {
	PublishedAt pgtype.Timestamptz
	EventID     pgtype.UUID
	ClaimToken  pgtype.UUID
}

func (q *Queries) MarkPlatformOutboxEventPublished(ctx context.Context, arg MarkPlatformOutboxEventPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPlatformOutboxEventPublished, arg.PublishedAt, arg.EventID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleClaimedPlatformOutboxEvent = `-- name: RescheduleClaimedPlatformOutboxEvent :execrows
UPDATE platform_outbox_events
SET publication_state = 'PENDING',
    next_attempt_at = $1,
    claimed_at = NULL,
    claim_token = NULL,
    lease_expires_at = NULL,
    last_failure_code = $2
WHERE event_id = $3
  AND publication_state = 'PROCESSING'
  AND claim_token = $4
`

type RescheduleClaimedPlatformOutboxEventParams struct {
	NextAttemptAt   pgtype.Timestamptz
	LastFailureCode pgtype.Text
	EventID         pgtype.UUID
	ClaimToken      pgtype.UUID
}

func (q *Queries) RescheduleClaimedPlatformOutboxEvent(ctx context.Context, arg RescheduleClaimedPlatformOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleClaimedPlatformOutboxEvent,
		arg.NextAttemptAt,
		arg.LastFailureCode,
		arg.EventID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
