// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: platform_audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendPlatformAuditEvent = `-- name: AppendPlatformAuditEvent :one
INSERT INTO audit_logs (
    audit_event_id,
    occurred_at,
    action,
    result,
    severity,
    actor_user_id,
    correlation_id,
    portfolio_id,
    transaction_id,
    correction_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING audit_event_id, occurred_at, action, result, severity, actor_user_id, correlation_id, session_id, token_family_id, network_identity_hash, user_agent, portfolio_id, transaction_id, correction_id
`

type AppendPlatformAuditEventParams struct {
	AuditEventID  pgtype.UUID
	OccurredAt    pgtype.Timestamptz
	Action        string
	Result        string
	Severity      string
	ActorUserID   pgtype.UUID
	CorrelationID string
	PortfolioID   pgtype.UUID
	TransactionID pgtype.UUID
	CorrectionID  pgtype.UUID
}

// Platform audit evidence is append-only. M3 references are allowlisted UUIDs;
// no request body, financial fields, or arbitrary metadata are accepted.
func (q *Queries) AppendPlatformAuditEvent(ctx context.Context, arg AppendPlatformAuditEventParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, appendPlatformAuditEvent,
		arg.AuditEventID,
		arg.OccurredAt,
		arg.Action,
		arg.Result,
		arg.Severity,
		arg.ActorUserID,
		arg.CorrelationID,
		arg.PortfolioID,
		arg.TransactionID,
		arg.CorrectionID,
	)
	var i AuditLog
	err := row.Scan(
		&i.AuditEventID,
		&i.OccurredAt,
		&i.Action,
		&i.Result,
		&i.Severity,
		&i.ActorUserID,
		&i.CorrelationID,
		&i.SessionID,
		&i.TokenFamilyID,
		&i.NetworkIdentityHash,
		&i.UserAgent,
		&i.PortfolioID,
		&i.TransactionID,
		&i.CorrectionID,
	)
	return i, err
}
