// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: corrections.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDirectTransactionCorrection = `-- name: GetDirectTransactionCorrection :one
SELECT correction_id, portfolio_id, original_transaction_id, reversal_transaction_id, replacement_transaction_id, created_by_user_id, created_at FROM transaction_corrections
WHERE portfolio_id = $1 AND original_transaction_id = $2
`

type GetDirectTransactionCorrectionParams struct {
	PortfolioID           pgtype.UUID
	OriginalTransactionID pgtype.UUID
}

// Supplies outgoing links without changing the original. A replacement retains
// its incoming creation links and can independently have an outgoing correction.
func (q *Queries) GetDirectTransactionCorrection(ctx context.Context, arg GetDirectTransactionCorrectionParams) (TransactionCorrection, error) {
	row := q.db.QueryRow(ctx, getDirectTransactionCorrection, arg.PortfolioID, arg.OriginalTransactionID)
	var i TransactionCorrection
	err := row.Scan(
		&i.CorrectionID,
		&i.PortfolioID,
		&i.OriginalTransactionID,
		&i.ReversalTransactionID,
		&i.ReplacementTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getPortfolioCorrection = `-- name: GetPortfolioCorrection :one
SELECT correction_id, portfolio_id, original_transaction_id, reversal_transaction_id, replacement_transaction_id, created_by_user_id, created_at FROM transaction_corrections
WHERE portfolio_id = $1 AND correction_id = $2
`

type GetPortfolioCorrectionParams struct {
	PortfolioID  pgtype.UUID
	CorrectionID pgtype.UUID
}

func (q *Queries) GetPortfolioCorrection(ctx context.Context, arg GetPortfolioCorrectionParams) (TransactionCorrection, error) {
	row := q.db.QueryRow(ctx, getPortfolioCorrection, arg.PortfolioID, arg.CorrectionID)
	var i TransactionCorrection
	err := row.Scan(
		&i.CorrectionID,
		&i.PortfolioID,
		&i.OriginalTransactionID,
		&i.ReversalTransactionID,
		&i.ReplacementTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransactionCorrection = `-- name: InsertTransactionCorrection :one
INSERT INTO transaction_corrections (
    correction_id, portfolio_id, original_transaction_id, reversal_transaction_id,
    replacement_transaction_id, created_by_user_id, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
) RETURNING correction_id, portfolio_id, original_transaction_id, reversal_transaction_id, replacement_transaction_id, created_by_user_id, created_at
`

type InsertTransactionCorrectionParams struct {
	CorrectionID             pgtype.UUID
	PortfolioID              pgtype.UUID
	OriginalTransactionID    pgtype.UUID
	ReversalTransactionID    pgtype.UUID
	ReplacementTransactionID pgtype.UUID
	CreatedByUserID          pgtype.UUID
	CreatedAt                pgtype.Timestamptz
}

// Caller-owned pgx.Tx; deferred FKs require matching reversal and replacement
// rows before commit. No original financial record is mutated.
func (q *Queries) InsertTransactionCorrection(ctx context.Context, arg InsertTransactionCorrectionParams) (TransactionCorrection, error) {
	row := q.db.QueryRow(ctx, insertTransactionCorrection,
		arg.CorrectionID,
		arg.PortfolioID,
		arg.OriginalTransactionID,
		arg.ReversalTransactionID,
		arg.ReplacementTransactionID,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i TransactionCorrection
	err := row.Scan(
		&i.CorrectionID,
		&i.PortfolioID,
		&i.OriginalTransactionID,
		&i.ReversalTransactionID,
		&i.ReplacementTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
