// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredTransactionIdempotencyBatch = `-- name: DeleteExpiredTransactionIdempotencyBatch :execrows
WITH expired AS (
    SELECT d.portfolio_id, d.command_scope, d.idempotency_key FROM transaction_idempotency AS d
    WHERE d.expires_at <= $1
    ORDER BY d.expires_at, d.portfolio_id, d.command_scope, d.idempotency_key
    LIMIT $2::int
    FOR UPDATE SKIP LOCKED
)
DELETE FROM transaction_idempotency AS i USING expired AS e
WHERE i.portfolio_id = e.portfolio_id AND i.command_scope = e.command_scope AND i.idempotency_key = e.idempotency_key
`

type DeleteExpiredTransactionIdempotencyBatchParams struct {
	AsOf      pgtype.Timestamptz
	BatchSize int32
}

// Future worker cleanup only. No ledger fact deletion. Multiple cleanup workers
// skip each other's row locks; concurrent renewed keys are not removed.
func (q *Queries) DeleteExpiredTransactionIdempotencyBatch(ctx context.Context, arg DeleteExpiredTransactionIdempotencyBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTransactionIdempotencyBatch, arg.AsOf, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredTransactionIdempotencyKey = `-- name: DeleteExpiredTransactionIdempotencyKey :execrows
DELETE FROM transaction_idempotency
WHERE portfolio_id = $1 AND command_scope = $2
    AND idempotency_key = $3 AND expires_at <= $4
`

type DeleteExpiredTransactionIdempotencyKeyParams struct {
	PortfolioID    pgtype.UUID
	CommandScope   string
	IdempotencyKey string
	AsOf           pgtype.Timestamptz
}

// Under the same advisory lock, before treating an expired key as a new command.
func (q *Queries) DeleteExpiredTransactionIdempotencyKey(ctx context.Context, arg DeleteExpiredTransactionIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTransactionIdempotencyKey,
		arg.PortfolioID,
		arg.CommandScope,
		arg.IdempotencyKey,
		arg.AsOf,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUnexpiredTransactionIdempotency = `-- name: GetUnexpiredTransactionIdempotency :one
SELECT portfolio_id, command_scope, idempotency_key, fingerprint_digest, target_transaction_id, primary_transaction_id, correction_id, created_at, expires_at FROM transaction_idempotency
WHERE portfolio_id = $1 AND command_scope = $2
    AND idempotency_key = $3 AND expires_at > $4
`

type GetUnexpiredTransactionIdempotencyParams struct {
	PortfolioID    pgtype.UUID
	CommandScope   string
	IdempotencyKey string
	AsOf           pgtype.Timestamptz
}

// Under the advisory lock. Fingerprint comparison/replay decisions are not SQL.
func (q *Queries) GetUnexpiredTransactionIdempotency(ctx context.Context, arg GetUnexpiredTransactionIdempotencyParams) (TransactionIdempotency, error) {
	row := q.db.QueryRow(ctx, getUnexpiredTransactionIdempotency,
		arg.PortfolioID,
		arg.CommandScope,
		arg.IdempotencyKey,
		arg.AsOf,
	)
	var i TransactionIdempotency
	err := row.Scan(
		&i.PortfolioID,
		&i.CommandScope,
		&i.IdempotencyKey,
		&i.FingerprintDigest,
		&i.TargetTransactionID,
		&i.PrimaryTransactionID,
		&i.CorrectionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertCompletedTransactionIdempotency = `-- name: InsertCompletedTransactionIdempotency :one
INSERT INTO transaction_idempotency (
    portfolio_id, command_scope, idempotency_key, fingerprint_digest,
    target_transaction_id, primary_transaction_id, correction_id, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8::timestamptz, $8::timestamptz + interval '8760 hours'
) RETURNING portfolio_id, command_scope, idempotency_key, fingerprint_digest, target_transaction_id, primary_transaction_id, correction_id, created_at, expires_at
`

type InsertCompletedTransactionIdempotencyParams struct {
	PortfolioID          pgtype.UUID
	CommandScope         string
	IdempotencyKey       string
	FingerprintDigest    []byte
	TargetTransactionID  pgtype.UUID
	PrimaryTransactionID pgtype.UUID
	CorrectionID         pgtype.UUID
	CompletedAt          pgtype.Timestamptz
}

// Same pgx.Tx as facts/correction/audit/outbox. completed_at is supplied at the
// final successful-write boundary, immediately before caller commit. 365 days
// means 8760 hours, independent of the connection's timezone/DST.
func (q *Queries) InsertCompletedTransactionIdempotency(ctx context.Context, arg InsertCompletedTransactionIdempotencyParams) (TransactionIdempotency, error) {
	row := q.db.QueryRow(ctx, insertCompletedTransactionIdempotency,
		arg.PortfolioID,
		arg.CommandScope,
		arg.IdempotencyKey,
		arg.FingerprintDigest,
		arg.TargetTransactionID,
		arg.PrimaryTransactionID,
		arg.CorrectionID,
		arg.CompletedAt,
	)
	var i TransactionIdempotency
	err := row.Scan(
		&i.PortfolioID,
		&i.CommandScope,
		&i.IdempotencyKey,
		&i.FingerprintDigest,
		&i.TargetTransactionID,
		&i.PrimaryTransactionID,
		&i.CorrectionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const lockTransactionIdempotency = `-- name: LockTransactionIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended(
    'transaction_idempotency:v1:' || $1::uuid::text || ':' ||
    length($2::text)::text || ':' || $2::text || ':' ||
    length($3::text)::text || ':' || $3::text, 0))
`

type LockTransactionIdempotencyParams struct {
	PortfolioID    pgtype.UUID
	CommandScope   string
	IdempotencyKey string
}

// Caller-owned pgx.Tx, acquired BEFORE the Portfolio sequence lock.
// PostgreSQL hashtextextended of the namespaced, length-framed text yields a
// deterministic signed bigint lock key. Hash collisions only over-serialize;
// the composite primary key is the final command-identity authority. Inputs
// are canonical UUID, allowlisted scope, validated opaque key, never credentials.
func (q *Queries) LockTransactionIdempotency(ctx context.Context, arg LockTransactionIdempotencyParams) error {
	_, err := q.db.Exec(ctx, lockTransactionIdempotency, arg.PortfolioID, arg.CommandScope, arg.IdempotencyKey)
	return err
}
