// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	TransactionID             pgtype.UUID
	PortfolioID               pgtype.UUID
	CreatedByUserID           pgtype.UUID
	Kind                      string
	AssetID                   pgtype.UUID
	AssetTypeSnapshot         pgtype.Text
	AssetExchangeSnapshot     pgtype.Text
	AssetCurrencySnapshot     pgtype.Text
	Quantity                  pgtype.Numeric
	UnitPrice                 pgtype.Numeric
	Fee                       pgtype.Numeric
	Amount                    pgtype.Numeric
	Currency                  string
	EffectiveAt               pgtype.Timestamptz
	PortfolioSequence         int64
	Note                      pgtype.Text
	ExternalReference         pgtype.Text
	ReversalOfTransactionID   pgtype.UUID
	CorrectionOfTransactionID pgtype.UUID
	OriginatingCorrectionID   pgtype.UUID
	CreatedAt                 pgtype.Timestamptz
}

type TransactionCorrection struct {
	CorrectionID             pgtype.UUID
	PortfolioID              pgtype.UUID
	OriginalTransactionID    pgtype.UUID
	ReversalTransactionID    pgtype.UUID
	ReplacementTransactionID pgtype.UUID
	CreatedByUserID          pgtype.UUID
	CreatedAt                pgtype.Timestamptz
}

type TransactionIdempotency struct {
	PortfolioID          pgtype.UUID
	CommandScope         string
	IdempotencyKey       string
	FingerprintDigest    []byte
	TargetTransactionID  pgtype.UUID
	PrimaryTransactionID pgtype.UUID
	CorrectionID         pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}
