// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sequences.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allocateCorrectionPortfolioSequences = `-- name: AllocateCorrectionPortfolioSequences :one
INSERT INTO transaction_portfolio_sequences (portfolio_id, next_sequence)
VALUES ($1, 3)
ON CONFLICT (portfolio_id) DO UPDATE
SET next_sequence = transaction_portfolio_sequences.next_sequence + 2
RETURNING (next_sequence - 2)::bigint AS reversal_sequence,
    (next_sequence - 1)::bigint AS replacement_sequence
`

type AllocateCorrectionPortfolioSequencesRow struct {
	ReversalSequence    int64
	ReplacementSequence int64
}

// Same lock order/transaction requirement as AllocateOnePortfolioSequence.
// Reserve reversal then replacement; rollback restores the counter.
func (q *Queries) AllocateCorrectionPortfolioSequences(ctx context.Context, portfolioID pgtype.UUID) (AllocateCorrectionPortfolioSequencesRow, error) {
	row := q.db.QueryRow(ctx, allocateCorrectionPortfolioSequences, portfolioID)
	var i AllocateCorrectionPortfolioSequencesRow
	err := row.Scan(&i.ReversalSequence, &i.ReplacementSequence)
	return i, err
}

const allocateOnePortfolioSequence = `-- name: AllocateOnePortfolioSequence :one
INSERT INTO transaction_portfolio_sequences (portfolio_id, next_sequence)
VALUES ($1, 2)
ON CONFLICT (portfolio_id) DO UPDATE
SET next_sequence = transaction_portfolio_sequences.next_sequence + 1
RETURNING (next_sequence - 1)::bigint AS portfolio_sequence
`

// Caller MUST hold the idempotency advisory lock first and use a caller-owned
// pgx.Tx. This UPSERT locks the Portfolio stream until commit/rollback; read
// the replay facts only AFTER allocation. Never allocate in autocommit mode.
func (q *Queries) AllocateOnePortfolioSequence(ctx context.Context, portfolioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, allocateOnePortfolioSequence, portfolioID)
	var portfolio_sequence int64
	err := row.Scan(&portfolio_sequence)
	return portfolio_sequence, err
}
