// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPortfolioTransaction = `-- name: GetPortfolioTransaction :one
SELECT transaction_id, portfolio_id, created_by_user_id, kind, asset_id, asset_type_snapshot, asset_exchange_snapshot, asset_currency_snapshot, quantity, unit_price, fee, amount, currency, effective_at, portfolio_sequence, note, external_reference, reversal_of_transaction_id, correction_of_transaction_id, originating_correction_id, created_at FROM transactions
WHERE portfolio_id = $1 AND transaction_id = $2
`

type GetPortfolioTransactionParams struct {
	PortfolioID   pgtype.UUID
	TransactionID pgtype.UUID
}

// Ownership must be proven through the Portfolio public boundary BEFORE use.
func (q *Queries) GetPortfolioTransaction(ctx context.Context, arg GetPortfolioTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getPortfolioTransaction, arg.PortfolioID, arg.TransactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.PortfolioID,
		&i.CreatedByUserID,
		&i.Kind,
		&i.AssetID,
		&i.AssetTypeSnapshot,
		&i.AssetExchangeSnapshot,
		&i.AssetCurrencySnapshot,
		&i.Quantity,
		&i.UnitPrice,
		&i.Fee,
		&i.Amount,
		&i.Currency,
		&i.EffectiveAt,
		&i.PortfolioSequence,
		&i.Note,
		&i.ExternalReference,
		&i.ReversalOfTransactionID,
		&i.CorrectionOfTransactionID,
		&i.OriginatingCorrectionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    transaction_id, portfolio_id, created_by_user_id, kind, asset_id,
    asset_type_snapshot, asset_exchange_snapshot, asset_currency_snapshot,
    quantity, unit_price, fee, amount, currency, effective_at, portfolio_sequence,
    note, external_reference, reversal_of_transaction_id,
    correction_of_transaction_id, originating_correction_id, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21
) RETURNING transaction_id, portfolio_id, created_by_user_id, kind, asset_id, asset_type_snapshot, asset_exchange_snapshot, asset_currency_snapshot, quantity, unit_price, fee, amount, currency, effective_at, portfolio_sequence, note, external_reference, reversal_of_transaction_id, correction_of_transaction_id, originating_correction_id, created_at
`

type InsertTransactionParams struct {
	TransactionID             pgtype.UUID
	PortfolioID               pgtype.UUID
	CreatedByUserID           pgtype.UUID
	Kind                      string
	AssetID                   pgtype.UUID
	AssetTypeSnapshot         pgtype.Text
	AssetExchangeSnapshot     pgtype.Text
	AssetCurrencySnapshot     pgtype.Text
	Quantity                  pgtype.Numeric
	UnitPrice                 pgtype.Numeric
	Fee                       pgtype.Numeric
	Amount                    pgtype.Numeric
	Currency                  string
	EffectiveAt               pgtype.Timestamptz
	PortfolioSequence         int64
	Note                      pgtype.Text
	ExternalReference         pgtype.Text
	ReversalOfTransactionID   pgtype.UUID
	CorrectionOfTransactionID pgtype.UUID
	OriginatingCorrectionID   pgtype.UUID
	CreatedAt                 pgtype.Timestamptz
}

// Caller-owned transaction after idempotency + sequence locks and application
// validation. Missing trade fee is supplied as exact zero by that application.
// Reversal/replacement rows must commit with their complete correction group.
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.TransactionID,
		arg.PortfolioID,
		arg.CreatedByUserID,
		arg.Kind,
		arg.AssetID,
		arg.AssetTypeSnapshot,
		arg.AssetExchangeSnapshot,
		arg.AssetCurrencySnapshot,
		arg.Quantity,
		arg.UnitPrice,
		arg.Fee,
		arg.Amount,
		arg.Currency,
		arg.EffectiveAt,
		arg.PortfolioSequence,
		arg.Note,
		arg.ExternalReference,
		arg.ReversalOfTransactionID,
		arg.CorrectionOfTransactionID,
		arg.OriginatingCorrectionID,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.PortfolioID,
		&i.CreatedByUserID,
		&i.Kind,
		&i.AssetID,
		&i.AssetTypeSnapshot,
		&i.AssetExchangeSnapshot,
		&i.AssetCurrencySnapshot,
		&i.Quantity,
		&i.UnitPrice,
		&i.Fee,
		&i.Amount,
		&i.Currency,
		&i.EffectiveAt,
		&i.PortfolioSequence,
		&i.Note,
		&i.ExternalReference,
		&i.ReversalOfTransactionID,
		&i.CorrectionOfTransactionID,
		&i.OriginatingCorrectionID,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetLedgerForReplay = `-- name: ListAssetLedgerForReplay :many
SELECT transaction_id, portfolio_id, created_by_user_id, kind, asset_id, asset_type_snapshot, asset_exchange_snapshot, asset_currency_snapshot, quantity, unit_price, fee, amount, currency, effective_at, portfolio_sequence, note, external_reference, reversal_of_transaction_id, correction_of_transaction_id, originating_correction_id, created_at FROM transactions
WHERE portfolio_id = $1 AND asset_id = $2
ORDER BY effective_at ASC, portfolio_sequence ASC, transaction_id ASC
`

type ListAssetLedgerForReplayParams struct {
	PortfolioID pgtype.UUID
	AssetID     pgtype.UUID
}

// Caller MUST hold the Portfolio sequence lock in the same pgx.Tx before
// reading. Raw immutable facts only: sign/equality/quantity replay stays Go-side.
func (q *Queries) ListAssetLedgerForReplay(ctx context.Context, arg ListAssetLedgerForReplayParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listAssetLedgerForReplay, arg.PortfolioID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.PortfolioID,
			&i.CreatedByUserID,
			&i.Kind,
			&i.AssetID,
			&i.AssetTypeSnapshot,
			&i.AssetExchangeSnapshot,
			&i.AssetCurrencySnapshot,
			&i.Quantity,
			&i.UnitPrice,
			&i.Fee,
			&i.Amount,
			&i.Currency,
			&i.EffectiveAt,
			&i.PortfolioSequence,
			&i.Note,
			&i.ExternalReference,
			&i.ReversalOfTransactionID,
			&i.CorrectionOfTransactionID,
			&i.OriginatingCorrectionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioTransactions = `-- name: ListPortfolioTransactions :many
SELECT transaction_id, portfolio_id, created_by_user_id, kind, asset_id, asset_type_snapshot, asset_exchange_snapshot, asset_currency_snapshot, quantity, unit_price, fee, amount, currency, effective_at, portfolio_sequence, note, external_reference, reversal_of_transaction_id, correction_of_transaction_id, originating_correction_id, created_at FROM transactions
WHERE portfolio_id = $1
    AND ($2::text IS NULL OR kind = $2)
    AND ($3::timestamptz IS NULL OR effective_at >= $3)
    AND ($4::timestamptz IS NULL OR effective_at <= $4)
    AND ($5::boolean OR kind <> 'REVERSAL')
    AND ($6::timestamptz IS NULL OR
        (effective_at, portfolio_sequence, transaction_id) <
        ($6::timestamptz, $7::bigint, $8::uuid))
ORDER BY effective_at DESC, portfolio_sequence DESC, transaction_id DESC
LIMIT $9::int
`

type ListPortfolioTransactionsParams struct {
	PortfolioID             pgtype.UUID
	Kind                    pgtype.Text
	EffectiveAtFrom         pgtype.Timestamptz
	EffectiveAtTo           pgtype.Timestamptz
	IncludeReversals        bool
	CursorEffectiveAt       pgtype.Timestamptz
	CursorPortfolioSequence pgtype.Int8
	CursorTransactionID     pgtype.UUID
	PageLimit               int32
}

// Caller validates filters/opaque cursor and supplies the full decoded tuple
// or three NULLs. Page limit is the contract limit (1..100); no offset paging.
func (q *Queries) ListPortfolioTransactions(ctx context.Context, arg ListPortfolioTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listPortfolioTransactions,
		arg.PortfolioID,
		arg.Kind,
		arg.EffectiveAtFrom,
		arg.EffectiveAtTo,
		arg.IncludeReversals,
		arg.CursorEffectiveAt,
		arg.CursorPortfolioSequence,
		arg.CursorTransactionID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.PortfolioID,
			&i.CreatedByUserID,
			&i.Kind,
			&i.AssetID,
			&i.AssetTypeSnapshot,
			&i.AssetExchangeSnapshot,
			&i.AssetCurrencySnapshot,
			&i.Quantity,
			&i.UnitPrice,
			&i.Fee,
			&i.Amount,
			&i.Currency,
			&i.EffectiveAt,
			&i.PortfolioSequence,
			&i.Note,
			&i.ExternalReference,
			&i.ReversalOfTransactionID,
			&i.CorrectionOfTransactionID,
			&i.OriginatingCorrectionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
