// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: assets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bootstrapCanonicalAsset = `-- name: BootstrapCanonicalAsset :one
INSERT INTO assets (
    asset_id,
    symbol,
    name,
    asset_type,
    exchange,
    currency,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'USD',
    $6,
    $7
)
ON CONFLICT (normalized_symbol, normalized_exchange) DO UPDATE
SET
    symbol = EXCLUDED.symbol,
    name = EXCLUDED.name,
    exchange = EXCLUDED.exchange,
    updated_at = EXCLUDED.updated_at
WHERE
    assets.asset_type = EXCLUDED.asset_type
    AND assets.currency = EXCLUDED.currency
RETURNING asset_id, symbol, normalized_symbol, name, asset_type, exchange, normalized_exchange, currency, created_at, updated_at
`

type BootstrapCanonicalAssetParams struct {
	AssetID   pgtype.UUID
	Symbol    string
	Name      string
	AssetType string
	Exchange  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// System-maintenance primitive only. It preserves an existing canonical ID and
// refuses to silently change a canonical Asset's type or currency.
func (q *Queries) BootstrapCanonicalAsset(ctx context.Context, arg BootstrapCanonicalAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, bootstrapCanonicalAsset,
		arg.AssetID,
		arg.Symbol,
		arg.Name,
		arg.AssetType,
		arg.Exchange,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.Symbol,
		&i.NormalizedSymbol,
		&i.Name,
		&i.AssetType,
		&i.Exchange,
		&i.NormalizedExchange,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCanonicalAssetByID = `-- name: GetCanonicalAssetByID :one
SELECT asset_id, symbol, normalized_symbol, name, asset_type, exchange, normalized_exchange, currency, created_at, updated_at
FROM assets
WHERE asset_id = $1
`

func (q *Queries) GetCanonicalAssetByID(ctx context.Context, assetID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getCanonicalAssetByID, assetID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.Symbol,
		&i.NormalizedSymbol,
		&i.Name,
		&i.AssetType,
		&i.Exchange,
		&i.NormalizedExchange,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchCanonicalAssets = `-- name: SearchCanonicalAssets :many
SELECT asset_id, symbol, normalized_symbol, name, asset_type, exchange, normalized_exchange, currency, created_at, updated_at
FROM assets
WHERE
    (
        $1::text IS NULL
        OR symbol ILIKE '%' || $1::text || '%'
        OR name ILIKE '%' || $1::text || '%'
    )
    AND (
        $2::text IS NULL
        OR asset_type = $2::text
    )
    AND (
        $3::text IS NULL
        OR (symbol, exchange, asset_id) > (
            $3::text,
            $4::text,
            $5::uuid
        )
    )
ORDER BY symbol ASC, exchange ASC, asset_id ASC
LIMIT $6
`

type SearchCanonicalAssetsParams struct {
	Search         pgtype.Text
	AssetType      pgtype.Text
	CursorSymbol   pgtype.Text
	CursorExchange pgtype.Text
	CursorAssetID  pgtype.UUID
	PageLimit      int32
}

// Cursor arguments are decoded, canonical ordering components. Cursor encoding
// remains a transport/application responsibility.
func (q *Queries) SearchCanonicalAssets(ctx context.Context, arg SearchCanonicalAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchCanonicalAssets,
		arg.Search,
		arg.AssetType,
		arg.CursorSymbol,
		arg.CursorExchange,
		arg.CursorAssetID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.Symbol,
			&i.NormalizedSymbol,
			&i.Name,
			&i.AssetType,
			&i.Exchange,
			&i.NormalizedExchange,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
