// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	AssetID            pgtype.UUID
	Symbol             string
	NormalizedSymbol   pgtype.Text
	Name               string
	AssetType          string
	Exchange           string
	NormalizedExchange pgtype.Text
	Currency           string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
