// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshSession struct {
	SessionID            pgtype.UUID
	TokenFamilyID        pgtype.UUID
	UserID               pgtype.UUID
	TokenDigest          []byte
	SessionState         string
	ReplacementSessionID pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	ReplacedAt           pgtype.Timestamptz
	IdleExpiresAt        pgtype.Timestamptz
	AbsoluteExpiresAt    pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	RevocationReason     pgtype.Text
	NetworkIdentityHash  pgtype.Text
	UserAgent            pgtype.Text
}

type User struct {
	UserID          pgtype.UUID
	NormalizedEmail string
	PasswordHash    string
	AccountStatus   string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DisabledAt      pgtype.Timestamptz
}
