// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: refresh_sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInactiveRefreshSessionsBefore = `-- name: DeleteInactiveRefreshSessionsBefore :execrows
DELETE FROM refresh_sessions
WHERE
    (session_state = 'replaced' AND replaced_at < $1)
    OR (session_state = 'revoked' AND revoked_at < $1)
    OR (session_state = 'expired' AND absolute_expires_at < $1)
`

// The caller supplies a separately approved retention cutoff; this query defines no retention period.
func (q *Queries) DeleteInactiveRefreshSessionsBefore(ctx context.Context, retentionCutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInactiveRefreshSessionsBefore, retentionCutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshSessionByID = `-- name: GetRefreshSessionByID :one
SELECT session_id, token_family_id, user_id, token_digest, session_state, replacement_session_id, created_at, replaced_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason, network_identity_hash, user_agent
FROM refresh_sessions
WHERE session_id = $1
`

func (q *Queries) GetRefreshSessionByID(ctx context.Context, sessionID pgtype.UUID) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByID, sessionID)
	var i RefreshSession
	err := row.Scan(
		&i.SessionID,
		&i.TokenFamilyID,
		&i.UserID,
		&i.TokenDigest,
		&i.SessionState,
		&i.ReplacementSessionID,
		&i.CreatedAt,
		&i.ReplacedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.NetworkIdentityHash,
		&i.UserAgent,
	)
	return i, err
}

const getRefreshSessionByTokenDigestForUpdate = `-- name: GetRefreshSessionByTokenDigestForUpdate :one
SELECT session_id, token_family_id, user_id, token_digest, session_state, replacement_session_id, created_at, replaced_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason, network_identity_hash, user_agent
FROM refresh_sessions
WHERE token_digest = $1
FOR UPDATE
`

// Must run inside the refresh transaction before any lifecycle transition.
func (q *Queries) GetRefreshSessionByTokenDigestForUpdate(ctx context.Context, tokenDigest []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenDigestForUpdate, tokenDigest)
	var i RefreshSession
	err := row.Scan(
		&i.SessionID,
		&i.TokenFamilyID,
		&i.UserID,
		&i.TokenDigest,
		&i.SessionState,
		&i.ReplacementSessionID,
		&i.CreatedAt,
		&i.ReplacedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.NetworkIdentityHash,
		&i.UserAgent,
	)
	return i, err
}

const insertRefreshSessionGeneration = `-- name: InsertRefreshSessionGeneration :one
INSERT INTO refresh_sessions (
    session_id,
    token_family_id,
    user_id,
    token_digest,
    session_state,
    replacement_session_id,
    created_at,
    replaced_at,
    idle_expires_at,
    absolute_expires_at,
    revoked_at,
    revocation_reason,
    network_identity_hash,
    user_agent
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'active',
    NULL,
    $5,
    NULL,
    $6,
    $7,
    NULL,
    NULL,
    $8,
    $9
)
RETURNING session_id, token_family_id, user_id, token_digest, session_state, replacement_session_id, created_at, replaced_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason, network_identity_hash, user_agent
`

type InsertRefreshSessionGenerationParams struct {
	SessionID           pgtype.UUID
	TokenFamilyID       pgtype.UUID
	UserID              pgtype.UUID
	TokenDigest         []byte
	CreatedAt           pgtype.Timestamptz
	IdleExpiresAt       pgtype.Timestamptz
	AbsoluteExpiresAt   pgtype.Timestamptz
	NetworkIdentityHash pgtype.Text
	UserAgent           pgtype.Text
}

// Initial and replacement generations are inserted as active. Replacement insertion must run
// in the same transaction as MarkActiveRefreshSessionReplaced.
func (q *Queries) InsertRefreshSessionGeneration(ctx context.Context, arg InsertRefreshSessionGenerationParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, insertRefreshSessionGeneration,
		arg.SessionID,
		arg.TokenFamilyID,
		arg.UserID,
		arg.TokenDigest,
		arg.CreatedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.NetworkIdentityHash,
		arg.UserAgent,
	)
	var i RefreshSession
	err := row.Scan(
		&i.SessionID,
		&i.TokenFamilyID,
		&i.UserID,
		&i.TokenDigest,
		&i.SessionState,
		&i.ReplacementSessionID,
		&i.CreatedAt,
		&i.ReplacedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.NetworkIdentityHash,
		&i.UserAgent,
	)
	return i, err
}

const listRefreshTokenFamilyState = `-- name: ListRefreshTokenFamilyState :many
SELECT session_id, token_family_id, user_id, token_digest, session_state, replacement_session_id, created_at, replaced_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason, network_identity_hash, user_agent
FROM refresh_sessions
WHERE token_family_id = $1
ORDER BY created_at, session_id
`

func (q *Queries) ListRefreshTokenFamilyState(ctx context.Context, tokenFamilyID pgtype.UUID) ([]RefreshSession, error) {
	rows, err := q.db.Query(ctx, listRefreshTokenFamilyState, tokenFamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshSession{}
	for rows.Next() {
		var i RefreshSession
		if err := rows.Scan(
			&i.SessionID,
			&i.TokenFamilyID,
			&i.UserID,
			&i.TokenDigest,
			&i.SessionState,
			&i.ReplacementSessionID,
			&i.CreatedAt,
			&i.ReplacedAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.NetworkIdentityHash,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActiveRefreshSessionReplaced = `-- name: MarkActiveRefreshSessionReplaced :one
UPDATE refresh_sessions
SET
    session_state = 'replaced',
    replacement_session_id = $1,
    replaced_at = $2
WHERE
    session_id = $3
    AND session_state = 'active'
RETURNING session_id, token_family_id, user_id, token_digest, session_state, replacement_session_id, created_at, replaced_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason, network_identity_hash, user_agent
`

type MarkActiveRefreshSessionReplacedParams struct {
	ReplacementSessionID pgtype.UUID
	ReplacedAt           pgtype.Timestamptz
	SessionID            pgtype.UUID
}

// Must run inside the same transaction as the replacement insert. The deferred self-FK permits
// the replacement ID to be recorded before the replacement row is inserted.
func (q *Queries) MarkActiveRefreshSessionReplaced(ctx context.Context, arg MarkActiveRefreshSessionReplacedParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, markActiveRefreshSessionReplaced, arg.ReplacementSessionID, arg.ReplacedAt, arg.SessionID)
	var i RefreshSession
	err := row.Scan(
		&i.SessionID,
		&i.TokenFamilyID,
		&i.UserID,
		&i.TokenDigest,
		&i.SessionState,
		&i.ReplacementSessionID,
		&i.CreatedAt,
		&i.ReplacedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.NetworkIdentityHash,
		&i.UserAgent,
	)
	return i, err
}

const markExpiredRefreshSessions = `-- name: MarkExpiredRefreshSessions :many
UPDATE refresh_sessions
SET session_state = 'expired'
WHERE
    session_state = 'active'
    AND (
        idle_expires_at <= $1
        OR absolute_expires_at <= $1
    )
RETURNING session_id
`

func (q *Queries) MarkExpiredRefreshSessions(ctx context.Context, asOf pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, markExpiredRefreshSessions, asOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var session_id pgtype.UUID
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :many
UPDATE refresh_sessions
SET
    session_state = 'revoked',
    revoked_at = $1,
    revocation_reason = $2
WHERE
    token_family_id = $3
    AND session_state <> 'revoked'
RETURNING session_id, token_family_id, user_id, token_digest, session_state, replacement_session_id, created_at, replaced_at, idle_expires_at, absolute_expires_at, revoked_at, revocation_reason, network_identity_hash, user_agent
`

type RevokeRefreshTokenFamilyParams struct {
	RevokedAt        pgtype.Timestamptz
	RevocationReason pgtype.Text
	TokenFamilyID    pgtype.UUID
}

// Must run inside the refresh/reuse transaction and affects only the supplied family.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) ([]RefreshSession, error) {
	rows, err := q.db.Query(ctx, revokeRefreshTokenFamily, arg.RevokedAt, arg.RevocationReason, arg.TokenFamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshSession{}
	for rows.Next() {
		var i RefreshSession
		if err := rows.Scan(
			&i.SessionID,
			&i.TokenFamilyID,
			&i.UserID,
			&i.TokenDigest,
			&i.SessionState,
			&i.ReplacementSessionID,
			&i.CreatedAt,
			&i.ReplacedAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.NetworkIdentityHash,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
