// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    normalized_email,
    password_hash,
    account_status,
    created_at,
    updated_at,
    disabled_at
) VALUES (
    $1,
    $2,
    $3,
    'active',
    $4,
    $4,
    NULL
)
RETURNING user_id, normalized_email, password_hash, account_status, created_at, updated_at, disabled_at
`

type CreateUserParams struct {
	UserID          pgtype.UUID
	NormalizedEmail string
	PasswordHash    string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.NormalizedEmail,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, normalized_email, password_hash, account_status, created_at, updated_at, disabled_at
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByNormalizedEmail = `-- name: GetUserByNormalizedEmail :one
SELECT user_id, normalized_email, password_hash, account_status, created_at, updated_at, disabled_at
FROM users
WHERE normalized_email = $1
`

func (q *Queries) GetUserByNormalizedEmail(ctx context.Context, normalizedEmail string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNormalizedEmail, normalizedEmail)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const updatePasswordHashCompareAndSwap = `-- name: UpdatePasswordHashCompareAndSwap :one
UPDATE users
SET
    password_hash = $1,
    updated_at = $2
WHERE
    user_id = $3
    AND password_hash = $4
RETURNING user_id, normalized_email, password_hash, account_status, created_at, updated_at, disabled_at
`

type UpdatePasswordHashCompareAndSwapParams struct {
	NewPasswordHash      string
	UpdatedAt            pgtype.Timestamptz
	UserID               pgtype.UUID
	ExpectedPasswordHash string
}

func (q *Queries) UpdatePasswordHashCompareAndSwap(ctx context.Context, arg UpdatePasswordHashCompareAndSwapParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePasswordHashCompareAndSwap,
		arg.NewPasswordHash,
		arg.UpdatedAt,
		arg.UserID,
		arg.ExpectedPasswordHash,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}
