// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Portfolio struct {
	PortfolioID    pgtype.UUID
	OwnerUserID    pgtype.UUID
	Name           string
	NormalizedName pgtype.Text
	BaseCurrency   string
	Status         string
	ArchivedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
