// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: portfolios.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOwnedActivePortfolio = `-- name: ArchiveOwnedActivePortfolio :one
UPDATE portfolios
SET
    status = 'ARCHIVED',
    archived_at = $1,
    updated_at = $2
WHERE
    portfolio_id = $3
    AND owner_user_id = $4
    AND status = 'ACTIVE'
RETURNING portfolio_id, owner_user_id, name, normalized_name, base_currency, status, archived_at, created_at, updated_at
`

type ArchiveOwnedActivePortfolioParams struct {
	ArchivedAt  pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PortfolioID pgtype.UUID
	OwnerUserID pgtype.UUID
}

// An archive retry is resolved by the future application layer through the
// owner-scoped read primitive; this mutation intentionally changes ACTIVE only.
func (q *Queries) ArchiveOwnedActivePortfolio(ctx context.Context, arg ArchiveOwnedActivePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, archiveOwnedActivePortfolio,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.PortfolioID,
		arg.OwnerUserID,
	)
	var i Portfolio
	err := row.Scan(
		&i.PortfolioID,
		&i.OwnerUserID,
		&i.Name,
		&i.NormalizedName,
		&i.BaseCurrency,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (
    portfolio_id,
    owner_user_id,
    name,
    base_currency,
    status,
    archived_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    'USD',
    'ACTIVE',
    NULL,
    $4,
    $4
)
RETURNING portfolio_id, owner_user_id, name, normalized_name, base_currency, status, archived_at, created_at, updated_at
`

type CreatePortfolioParams struct {
	PortfolioID pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, createPortfolio,
		arg.PortfolioID,
		arg.OwnerUserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Portfolio
	err := row.Scan(
		&i.PortfolioID,
		&i.OwnerUserID,
		&i.Name,
		&i.NormalizedName,
		&i.BaseCurrency,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedPortfolioByID = `-- name: GetOwnedPortfolioByID :one
SELECT portfolio_id, owner_user_id, name, normalized_name, base_currency, status, archived_at, created_at, updated_at
FROM portfolios
WHERE
    portfolio_id = $1
    AND owner_user_id = $2
`

type GetOwnedPortfolioByIDParams struct {
	PortfolioID pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) GetOwnedPortfolioByID(ctx context.Context, arg GetOwnedPortfolioByIDParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, getOwnedPortfolioByID, arg.PortfolioID, arg.OwnerUserID)
	var i Portfolio
	err := row.Scan(
		&i.PortfolioID,
		&i.OwnerUserID,
		&i.Name,
		&i.NormalizedName,
		&i.BaseCurrency,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnedPortfoliosByStatus = `-- name: ListOwnedPortfoliosByStatus :many
SELECT portfolio_id, owner_user_id, name, normalized_name, base_currency, status, archived_at, created_at, updated_at
FROM portfolios
WHERE
    owner_user_id = $1
    AND status = $2
ORDER BY updated_at DESC, portfolio_id ASC
`

type ListOwnedPortfoliosByStatusParams struct {
	OwnerUserID pgtype.UUID
	Status      string
}

func (q *Queries) ListOwnedPortfoliosByStatus(ctx context.Context, arg ListOwnedPortfoliosByStatusParams) ([]Portfolio, error) {
	rows, err := q.db.Query(ctx, listOwnedPortfoliosByStatus, arg.OwnerUserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.PortfolioID,
			&i.OwnerUserID,
			&i.Name,
			&i.NormalizedName,
			&i.BaseCurrency,
			&i.Status,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOwnedActivePortfolioName = `-- name: UpdateOwnedActivePortfolioName :one
UPDATE portfolios
SET
    name = $1,
    updated_at = $2
WHERE
    portfolio_id = $3
    AND owner_user_id = $4
    AND status = 'ACTIVE'
RETURNING portfolio_id, owner_user_id, name, normalized_name, base_currency, status, archived_at, created_at, updated_at
`

type UpdateOwnedActivePortfolioNameParams struct {
	Name        string
	UpdatedAt   pgtype.Timestamptz
	PortfolioID pgtype.UUID
	OwnerUserID pgtype.UUID
}

// The caller must classify no-row and uniqueness outcomes without exposing
// database details as public HTTP errors.
func (q *Queries) UpdateOwnedActivePortfolioName(ctx context.Context, arg UpdateOwnedActivePortfolioNameParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, updateOwnedActivePortfolioName,
		arg.Name,
		arg.UpdatedAt,
		arg.PortfolioID,
		arg.OwnerUserID,
	)
	var i Portfolio
	err := row.Scan(
		&i.PortfolioID,
		&i.OwnerUserID,
		&i.Name,
		&i.NormalizedName,
		&i.BaseCurrency,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
